apiVersion: apps/v1
kind: Deployment
metadata:
  name: peakapp-uat
  labels:
    app: peakapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peakapp
  template:
    metadata:
      labels:
        app: peakapp
        environment: uat
    spec:
      containers:
      - name: peakapp
        image: localhost.localdomain:5200/skippy
        ports:
        - containerPort: 5200
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2"
          requests:
            memory: "512Mi"
            cpu: "1"
